name: basket_craft
version: '1.0'
config-version: 2

profile: basket_craft

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  basket_craft:
    +materialized: table